In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# execute in performance
size = 1_000_0000

# time
py_list = list(range(size))
start = time.time()
sq_list=[x**2 for x in py_list]
end = time.time()
print(f'python list time = {end-start} seconds')

# numpy arrays
np_arr = np.array(py_list)
start = time.time()
# vectorization
sq_array = np_arr ** 2
end = time.time()
print(f'numpy array time = {end-start}')

python list time = 2.0011768341064453 seconds
numpy array time = 0.09721899032592773


In [4]:
# memory
import  sys
print(f'size of py list = {sys.getsizeof(py_list)* len(py_list)} bytes')
print(f'size of numpy array = {np_arr.nbytes} bytes')

size of py list = 800000560000000 bytes
size of numpy array = 80000000 bytes


# numpy arrays

In [5]:
arr1 = np.array([1,2,3,4,5])
print(arr1,type(arr1),arr1.dtype)

arr2 = np.array([1,2,3,6,7,'prime'])
print(arr2,type(arr2),arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '6' '7' 'prime'] <class 'numpy.ndarray'> <U21


In [6]:
print(arr1.shape)
print(arr2.shape)

(5,)
(6,)


In [7]:
# 2d array
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3,type(arr3))
print(arr3.shape) # dimensions rows*columns

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
(3, 3)


In [8]:
# create numpy arrays from scratch
arr4 = np.zeros((2,3),dtype="int64") # prefill np.zeros(r,c)
arr4

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
arr5 = np.ones((2,3))
print(arr5,arr5.shape)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [10]:
arr6 = np.full((3,4),100)
print(arr6)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [11]:
arr7 = np.eye(4) #identity mattrix
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# range(start,end,step)
arr8 = np.arange(1,10,2)
print(arr8,arr8.shape)

[1 3 5 7 9] (5,)


In [13]:
arr9 = np.linspace(1,100,3) # evenly spaced 
print(arr9)

[  1.   50.5 100. ]


In [14]:
# properties
arr10 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr10.shape) # dimensions = m*n
print(arr10.size) # total elements = 9
print(arr10.dtype)
print(arr10.ndim)

float_arr = arr10.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# Operations on Numpy arrays

In [15]:
# reshaping
arr11 = np.array([[1,2,3],[4,5,6]])
print(arr11, arr11.shape,arr11.size)

print("---------------------------------")

reshaped_arr = arr11.reshape((3,2))
print(reshaped_arr, reshaped_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3) 6
---------------------------------
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [16]:
# flatten()
flattened_arr = arr11.flatten() # 2D---> 1D
print(flattened_arr, flattened_arr.shape)

[1 2 3 4 5 6] (6,)


In [17]:
# Indexing (1D and 2D array)
arr12 = np.array([1,2,3,4,5])
print(arr12[0])
print(arr12[1])
print(arr12[4])

1
2
5


In [18]:
arr13 = np.array([[1,2,3],[4,5,6]])
print(arr13,arr13.shape)

print(arr13[0][1])
print(arr13[1][2])

[[1 2 3]
 [4 5 6]] (2, 3)
2
6


In [19]:
# Fancy indexing
arr14 = np.array([1,2,3,4,5])
indx = [0,1,3]
print(arr14[indx])

[1 2 4]


In [20]:
# Boolean indexing
arr15 = np.array([1,2,3,4,5])
print(arr15[arr15>3])
print(arr15[arr15%2==0]) # even values

[4 5]
[2 4]


In [21]:
#slicing
arr16 = np.array([1,2,3,4,5])
# (start,end,step)
print(arr16[1:4])
print(arr16[1:])
print(arr16[:4])
print(arr16[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [22]:
# copy vs view
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [23]:
arr17 = np.array([1,2,3,4,5])
sub_arr = arr17[1:3]
print(sub_arr)
sub_arr[0]=100
print(sub_arr)
print(arr17)

[2 3]
[100   3]
[  1 100   3   4   5]


In [24]:
# data types
arr18 = np.array([1,2,3.14,4,5,"prime"])
print(arr18,arr18.dtype)

['1' '2' '3.14' '4' '5' 'prime'] <U32


In [25]:
# complex num
arr19 = np.array([3+5j])
arr20 = np.array([2+3j])
print(arr19+arr20)

[5.+8.j]


# Axes in Multi dimensional array



In [26]:
# Multi dimensional array

arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2D)
print(np.sum(arr2D)) # sum

sum_of_columns = np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [27]:
# 3D array
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [28]:
# indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

4
9


In [29]:
# slicing
print(arr3D[:,0,:]) # first row from both layers
print(arr3D[:,:,0]) # first column from both layers

[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [30]:
# Data manipulation
arr3D[:,:,0] = 99
print(arr3D)

[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]


# vectorization and Broad Casting

In [31]:
# vectorization
arr21 = np.array([1,2,3,4,5])
arr22 = np.array([6,7,8,9,10])

print(arr21 **2)
print(arr21 + 10)
print(arr21+arr22)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [32]:
# Broad casting
arr23 = np.array([1,2,3,4,5])
print(arr23 + 5) # behid the scenes boadcasting is used

[ 6  7  8  9 10]


In [33]:
arr23 = np.array([1,2,3,4,5])
arr24 = np.array([[1,2,3,4,5],
                  [5,6,7,8,9]])
print(arr23 + arr24)
print(arr23.shape, arr24.shape)

# Because the arr23 is (5*1) there is 1 and by the rule of broadcasting it is possible
# to broadcast

[[ 2  4  6  8 10]
 [ 6  8 10 12 14]]
(5,) (2, 5)


In [34]:
arr25 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]) # 3*5
arr26 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) # 2*5
# by rule of braodcasting it is not possible to add these two arrays
print(arr25 + arr26)

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

# Normalization

In [35]:
# normalization
arr27 = np.array([[1,2],[3,4]])
mean = np.mean(arr27)
std = np.std(arr27)
norm_arr = (arr27-mean)/std # standard normalization
print(norm_arr)
print(mean)
print(std)

# After normalization mean becomes 0 and std deviation becomes 1

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


# Important mathematical functions

In [36]:
# Aggregation()
arr28 = np.array([1,2,3,14,5])

print(np.sum(arr28)) # sum 
print(np.prod(arr28)) # prod
print(np.min(arr28)) # min
print(np.max(arr28)) # max
print(np.argmin(arr28)) # returns index of min value
print(np.argmax(arr28)) # returns index of max value
print(np.mean(arr28)) # mean
print(np.std(arr28)) # standard deviation
print(np.median(arr28)) # median
print(np.var(arr28))

25
420
1
14
0
3
5.0
4.69041575982343
3.0
22.0


In [37]:
# power function
arr28 = np.array([1,2,3,14,5])

print(np.square(arr28)) # square of all the elements
print(np.sqrt(arr28)) # square root
print(np.pow(arr28,3))

[  1   4   9 196  25]
[1.         1.41421356 1.73205081 3.74165739 2.23606798]
[   1    8   27 2744  125]


In [38]:
# log functions
arr28 = np.array([1,2,3,14,5])

print(np.log(arr28)) # natural logs
print(np.log10(arr28)) # log base 10
print(np.log2(arr28)) # log base 2
print(np.exp(arr28))

[0.         0.69314718 1.09861229 2.63905733 1.60943791]
[0.         0.30103    0.47712125 1.14612804 0.69897   ]
[0.         1.         1.5849625  3.80735492 2.32192809]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 1.20260428e+06
 1.48413159e+02]


In [39]:
# rounding functions
arr29 = np.array([1.6,2.5,3.2,14.4,5])

print(np.round(arr29))
print(np.ceil(arr29)) # round up
print(np.floor(arr29)) # round down
print(np.trunc(arr29)) # romoves all value after point

[ 2.  2.  3. 14.  5.]
[ 2.  3.  4. 15.  5.]
[ 1.  2.  3. 14.  5.]
[ 1.  2.  3. 14.  5.]


In [40]:
# Extras functions
arr30 = np.array([55,-2,2,3,14,-1,3,14,-5])

print(np.unique(arr30)) # unique
print(np.sort(arr30)) # sorts the values
print(np.abs(arr30)) # negative lai pani positive banayeera return grxa

[-5 -2 -1  2  3 14 55]
[-5 -2 -1  2  3  3 14 14 55]
[55  2  2  3 14  1  3 14  5]
